### ISSUE TITLE
Add a wet martini

### ISSUE THREAD

**Issue by pudkipz** [pudkipz/CryptoGame#3]
This game is still very early in development, and we are missing a lot of things. Among these is the wet martini - a drink you can order from the bar in Bitown. It would be really awesome if you wanted to come up with a simple design for the wet martini. This would include doing two things (but if you only want to do one/some of them, then that would be okay too):

- **Drawing a picture.** You can find a few items in the pictures folder (beer, pickle, pickle juice). The wet martini should be in the same format: a .png file 75x75 px.

- **Writing an item description.** Every item has a descrption that shows in the inventory, and the wet martini will not be an exception. All text files are located in the text_files folder. Read the readme in that folder and add a line in descriptions.txt.

Lastly it will also have to be added into the game by adding a few lines in main.py, but since that file is so messy at the moment, I would prefer to add it myself.

If you can think of any other weird/random/quirky items that we could add to the game (it really could be anything!), please, do leave a suggestion!

**Comment by dhevi** [comment]
Gave this one a shot -- please see #4 and let me know what you think!

**Comment by pudkipz** [comment]
That looks very nice! I'll add it to the game, thank you very much!

**Comment by pudkipz** [comment]
@dhevi Hi again, just wanted to say that the wet martini is now in the game, and although it doesn't do anything, you can get it from the "babir" (bar) by asking for a "webit mabirtibinibi".
