### ISSUE TITLE
Add an item to the game

### ISSUE THREAD

**Issue by pudkipz** [pudkipz/CryptoGame#5]
This game is still very early in development, and we are missing a lot of things, among these, _ideas_. It would be really awesome if you wanted to come up with an item that we could add to the game - we are looking for all sorts of crazy stuff, but if you can't come up with anything, we could possibly use things like jars, fruits (of your choice), cups, grappling hooks...

This would include doing three things (but if you only want to do one/some of them, then that would be okay too):

- **Drawing a picture.** You can find a few items in the pictures folder (beer, pickle, pickle juice). Your item should be in the same format: a .png file 75x75 px.

- **Writing an item description.** Every item has a description that shows up in the inventory, and your item will not be an exception. All text files are located in the text_files folder. Read the readme in that folder and add a line in descriptions.txt.

- **Write in the new_items.md.** Here you write which item it is, what the picture file name is, what the description ID is, and finally how it could be used in the game, or any kind of explanation. The last part isn't very strict, so if you don't know what to write there, just leave it blank.

Lastly it will also have to actually be added to the game, but for obvious reasons that will have to wait.

Thank you for reading, and I hope you will consider helping us out!

**Comment by ArleneAndrews** [comment]
I'm guessing D and D type items? I may be able to pull something together, or add documentation. :)

**Comment by pudkipz** [comment]
@ArleneAndrews Hi! I'm afraid I don't know what you mean by D and D type items.
